### ISSUE TITLE
表头显示不全

### ISSUE THREAD

**Issue by guliansheng** [mnm1001/ex-table-column#2]
内容宽度小于表头宽度时，表头显示不全，能不能同时计算表头和内容的宽度，取两者宽度较大的为列宽

**Comment by mnm1001** [comment]
941beeb7caa740c5a0b8081d10205dcd0fd3b4ea

`npm update ex-table-column@1.1.0 --save`

Then you can add prop `:fitHeader: "true"` to achieve this feature.
